name: iport_parser
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  http: ^0.13.4
  teledart: ^0.2.1

dev_dependencies:
  lints: ^1.0.0
